# Auto-generated by gen_dockerfile.py
# Each COPY is a separate layer, all under 10 GB to satisfy GHCR.
# Repo: unsloth/Qwen3.8-Flash-Next
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates bash coreutils && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /model
RUN mkdir -p /model/chunks

# Manifest first (small layer, helps debugging)
COPY manifest.json /model/manifest.json

# --- chunks (one COPY per chunk = one layer per chunk) ---
COPY chunks/.gitattributes.part000 /model/chunks/.gitattributes.part000
COPY chunks/LICENSE.part000 /model/chunks/LICENSE.part000
COPY chunks/README.md.part000 /model/chunks/README.md.part000
COPY chunks/chat_template.jinja.part000 /model/chunks/chat_template.jinja.part000
COPY chunks/config.json.part000 /model/chunks/config.json.part000
COPY chunks/generation_config.json.part000 /model/chunks/generation_config.json.part000
COPY chunks/merges.txt.part000 /model/chunks/merges.txt.part000
COPY chunks/model-00001-of-00131.safetensors.part000 /model/chunks/model-00001-of-00131.safetensors.part000
COPY chunks/model-00002-of-00131.safetensors.part000 /model/chunks/model-00002-of-00131.safetensors.part000
COPY chunks/model-00003-of-00131.safetensors.part000 /model/chunks/model-00003-of-00131.safetensors.part000
COPY chunks/model-00004-of-00131.safetensors.part000 /model/chunks/model-00004-of-00131.safetensors.part000
COPY chunks/model-00005-of-00131.safetensors.part000 /model/chunks/model-00005-of-00131.safetensors.part000
COPY chunks/model-00006-of-00131.safetensors.part000 /model/chunks/model-00006-of-00131.safetensors.part000
COPY chunks/model-00007-of-00131.safetensors.part000 /model/chunks/model-00007-of-00131.safetensors.part000
COPY chunks/model-00008-of-00131.safetensors.part000 /model/chunks/model-00008-of-00131.safetensors.part000
COPY chunks/model-00009-of-00131.safetensors.part000 /model/chunks/model-00009-of-00131.safetensors.part000
COPY chunks/model-00010-of-00131.safetensors.part000 /model/chunks/model-00010-of-00131.safetensors.part000
COPY chunks/model-00011-of-00131.safetensors.part000 /model/chunks/model-00011-of-00131.safetensors.part000
COPY chunks/model-00012-of-00131.safetensors.part000 /model/chunks/model-00012-of-00131.safetensors.part000
COPY chunks/model-00013-of-00131.safetensors.part000 /model/chunks/model-00013-of-00131.safetensors.part000
COPY chunks/model-00014-of-00131.safetensors.part000 /model/chunks/model-00014-of-00131.safetensors.part000
COPY chunks/model-00015-of-00131.safetensors.part000 /model/chunks/model-00015-of-00131.safetensors.part000
COPY chunks/model-00016-of-00131.safetensors.part000 /model/chunks/model-00016-of-00131.safetensors.part000
COPY chunks/model-00017-of-00131.safetensors.part000 /model/chunks/model-00017-of-00131.safetensors.part000
COPY chunks/model-00018-of-00131.safetensors.part000 /model/chunks/model-00018-of-00131.safetensors.part000
COPY chunks/model-00019-of-00131.safetensors.part000 /model/chunks/model-00019-of-00131.safetensors.part000
COPY chunks/model-00020-of-00131.safetensors.part000 /model/chunks/model-00020-of-00131.safetensors.part000
COPY chunks/model-00021-of-00131.safetensors.part000 /model/chunks/model-00021-of-00131.safetensors.part000
COPY chunks/model-00022-of-00131.safetensors.part000 /model/chunks/model-00022-of-00131.safetensors.part000
COPY chunks/model-00023-of-00131.safetensors.part000 /model/chunks/model-00023-of-00131.safetensors.part000
COPY chunks/model-00024-of-00131.safetensors.part000 /model/chunks/model-00024-of-00131.safetensors.part000
COPY chunks/model-00025-of-00131.safetensors.part000 /model/chunks/model-00025-of-00131.safetensors.part000
COPY chunks/model-00026-of-00131.safetensors.part000 /model/chunks/model-00026-of-00131.safetensors.part000
COPY chunks/model-00027-of-00131.safetensors.part000 /model/chunks/model-00027-of-00131.safetensors.part000
COPY chunks/model-00028-of-00131.safetensors.part000 /model/chunks/model-00028-of-00131.safetensors.part000
COPY chunks/model-00029-of-00131.safetensors.part000 /model/chunks/model-00029-of-00131.safetensors.part000
COPY chunks/model-00030-of-00131.safetensors.part000 /model/chunks/model-00030-of-00131.safetensors.part000
COPY chunks/model-00031-of-00131.safetensors.part000 /model/chunks/model-00031-of-00131.safetensors.part000
COPY chunks/model-00032-of-00131.safetensors.part000 /model/chunks/model-00032-of-00131.safetensors.part000
COPY chunks/model-00033-of-00131.safetensors.part000 /model/chunks/model-00033-of-00131.safetensors.part000
COPY chunks/model-00034-of-00131.safetensors.part000 /model/chunks/model-00034-of-00131.safetensors.part000
COPY chunks/model-00035-of-00131.safetensors.part000 /model/chunks/model-00035-of-00131.safetensors.part000
COPY chunks/model-00036-of-00131.safetensors.part000 /model/chunks/model-00036-of-00131.safetensors.part000
COPY chunks/model-00037-of-00131.safetensors.part000 /model/chunks/model-00037-of-00131.safetensors.part000
COPY chunks/model-00038-of-00131.safetensors.part000 /model/chunks/model-00038-of-00131.safetensors.part000
COPY chunks/model-00039-of-00131.safetensors.part000 /model/chunks/model-00039-of-00131.safetensors.part000
COPY chunks/model-00040-of-00131.safetensors.part000 /model/chunks/model-00040-of-00131.safetensors.part000
COPY chunks/model-00041-of-00131.safetensors.part000 /model/chunks/model-00041-of-00131.safetensors.part000
COPY chunks/model-00042-of-00131.safetensors.part000 /model/chunks/model-00042-of-00131.safetensors.part000
COPY chunks/model-00043-of-00131.safetensors.part000 /model/chunks/model-00043-of-00131.safetensors.part000
COPY chunks/model-00044-of-00131.safetensors.part000 /model/chunks/model-00044-of-00131.safetensors.part000
COPY chunks/model-00045-of-00131.safetensors.part000 /model/chunks/model-00045-of-00131.safetensors.part000
COPY chunks/model-00046-of-00131.safetensors.part000 /model/chunks/model-00046-of-00131.safetensors.part000
COPY chunks/model-00047-of-00131.safetensors.part000 /model/chunks/model-00047-of-00131.safetensors.part000
COPY chunks/model-00048-of-00131.safetensors.part000 /model/chunks/model-00048-of-00131.safetensors.part000
COPY chunks/model-00049-of-00131.safetensors.part000 /model/chunks/model-00049-of-00131.safetensors.part000
COPY chunks/model-00050-of-00131.safetensors.part000 /model/chunks/model-00050-of-00131.safetensors.part000
COPY chunks/model-00051-of-00131.safetensors.part000 /model/chunks/model-00051-of-00131.safetensors.part000
COPY chunks/model-00052-of-00131.safetensors.part000 /model/chunks/model-00052-of-00131.safetensors.part000
COPY chunks/model-00053-of-00131.safetensors.part000 /model/chunks/model-00053-of-00131.safetensors.part000
COPY chunks/model-00054-of-00131.safetensors.part000 /model/chunks/model-00054-of-00131.safetensors.part000
COPY chunks/model-00055-of-00131.safetensors.part000 /model/chunks/model-00055-of-00131.safetensors.part000
COPY chunks/model-00056-of-00131.safetensors.part000 /model/chunks/model-00056-of-00131.safetensors.part000
COPY chunks/model-00057-of-00131.safetensors.part000 /model/chunks/model-00057-of-00131.safetensors.part000
COPY chunks/model-00058-of-00131.safetensors.part000 /model/chunks/model-00058-of-00131.safetensors.part000
COPY chunks/model-00059-of-00131.safetensors.part000 /model/chunks/model-00059-of-00131.safetensors.part000
COPY chunks/model-00060-of-00131.safetensors.part000 /model/chunks/model-00060-of-00131.safetensors.part000
COPY chunks/model-00061-of-00131.safetensors.part000 /model/chunks/model-00061-of-00131.safetensors.part000
COPY chunks/model-00062-of-00131.safetensors.part000 /model/chunks/model-00062-of-00131.safetensors.part000
COPY chunks/model-00063-of-00131.safetensors.part000 /model/chunks/model-00063-of-00131.safetensors.part000
COPY chunks/model-00064-of-00131.safetensors.part000 /model/chunks/model-00064-of-00131.safetensors.part000
COPY chunks/model-00065-of-00131.safetensors.part000 /model/chunks/model-00065-of-00131.safetensors.part000
COPY chunks/model-00066-of-00131.safetensors.part000 /model/chunks/model-00066-of-00131.safetensors.part000
COPY chunks/model-00067-of-00131.safetensors.part000 /model/chunks/model-00067-of-00131.safetensors.part000
COPY chunks/model-00068-of-00131.safetensors.part000 /model/chunks/model-00068-of-00131.safetensors.part000
COPY chunks/model-00069-of-00131.safetensors.part000 /model/chunks/model-00069-of-00131.safetensors.part000
COPY chunks/model-00070-of-00131.safetensors.part000 /model/chunks/model-00070-of-00131.safetensors.part000
COPY chunks/model-00071-of-00131.safetensors.part000 /model/chunks/model-00071-of-00131.safetensors.part000
COPY chunks/model-00072-of-00131.safetensors.part000 /model/chunks/model-00072-of-00131.safetensors.part000
COPY chunks/model-00073-of-00131.safetensors.part000 /model/chunks/model-00073-of-00131.safetensors.part000
COPY chunks/model-00074-of-00131.safetensors.part000 /model/chunks/model-00074-of-00131.safetensors.part000
COPY chunks/model-00075-of-00131.safetensors.part000 /model/chunks/model-00075-of-00131.safetensors.part000
COPY chunks/model-00076-of-00131.safetensors.part000 /model/chunks/model-00076-of-00131.safetensors.part000
COPY chunks/model-00077-of-00131.safetensors.part000 /model/chunks/model-00077-of-00131.safetensors.part000
COPY chunks/model-00078-of-00131.safetensors.part000 /model/chunks/model-00078-of-00131.safetensors.part000
COPY chunks/model-00079-of-00131.safetensors.part000 /model/chunks/model-00079-of-00131.safetensors.part000
COPY chunks/model-00080-of-00131.safetensors.part000 /model/chunks/model-00080-of-00131.safetensors.part000
COPY chunks/model-00081-of-00131.safetensors.part000 /model/chunks/model-00081-of-00131.safetensors.part000
COPY chunks/model-00082-of-00131.safetensors.part000 /model/chunks/model-00082-of-00131.safetensors.part000
COPY chunks/model-00083-of-00131.safetensors.part000 /model/chunks/model-00083-of-00131.safetensors.part000
COPY chunks/model-00084-of-00131.safetensors.part000 /model/chunks/model-00084-of-00131.safetensors.part000
COPY chunks/model-00085-of-00131.safetensors.part000 /model/chunks/model-00085-of-00131.safetensors.part000
COPY chunks/model-00086-of-00131.safetensors.part000 /model/chunks/model-00086-of-00131.safetensors.part000
COPY chunks/model-00087-of-00131.safetensors.part000 /model/chunks/model-00087-of-00131.safetensors.part000
COPY chunks/model-00088-of-00131.safetensors.part000 /model/chunks/model-00088-of-00131.safetensors.part000
COPY chunks/model-00089-of-00131.safetensors.part000 /model/chunks/model-00089-of-00131.safetensors.part000
COPY chunks/model-00090-of-00131.safetensors.part000 /model/chunks/model-00090-of-00131.safetensors.part000
COPY chunks/model-00091-of-00131.safetensors.part000 /model/chunks/model-00091-of-00131.safetensors.part000
COPY chunks/model-00092-of-00131.safetensors.part000 /model/chunks/model-00092-of-00131.safetensors.part000
COPY chunks/model-00093-of-00131.safetensors.part000 /model/chunks/model-00093-of-00131.safetensors.part000
COPY chunks/model-00094-of-00131.safetensors.part000 /model/chunks/model-00094-of-00131.safetensors.part000
COPY chunks/model-00095-of-00131.safetensors.part000 /model/chunks/model-00095-of-00131.safetensors.part000
COPY chunks/model-00096-of-00131.safetensors.part000 /model/chunks/model-00096-of-00131.safetensors.part000
COPY chunks/model-00097-of-00131.safetensors.part000 /model/chunks/model-00097-of-00131.safetensors.part000
COPY chunks/model-00098-of-00131.safetensors.part000 /model/chunks/model-00098-of-00131.safetensors.part000
COPY chunks/model-00099-of-00131.safetensors.part000 /model/chunks/model-00099-of-00131.safetensors.part000
COPY chunks/model-00100-of-00131.safetensors.part000 /model/chunks/model-00100-of-00131.safetensors.part000
COPY chunks/model-00101-of-00131.safetensors.part000 /model/chunks/model-00101-of-00131.safetensors.part000
COPY chunks/model-00102-of-00131.safetensors.part000 /model/chunks/model-00102-of-00131.safetensors.part000
COPY chunks/model-00103-of-00131.safetensors.part000 /model/chunks/model-00103-of-00131.safetensors.part000
COPY chunks/model-00104-of-00131.safetensors.part000 /model/chunks/model-00104-of-00131.safetensors.part000
COPY chunks/model-00105-of-00131.safetensors.part000 /model/chunks/model-00105-of-00131.safetensors.part000
COPY chunks/model-00106-of-00131.safetensors.part000 /model/chunks/model-00106-of-00131.safetensors.part000
COPY chunks/model-00107-of-00131.safetensors.part000 /model/chunks/model-00107-of-00131.safetensors.part000
COPY chunks/model-00108-of-00131.safetensors.part000 /model/chunks/model-00108-of-00131.safetensors.part000
COPY chunks/model-00109-of-00131.safetensors.part000 /model/chunks/model-00109-of-00131.safetensors.part000
COPY chunks/model-00110-of-00131.safetensors.part000 /model/chunks/model-00110-of-00131.safetensors.part000
COPY chunks/model-00111-of-00131.safetensors.part000 /model/chunks/model-00111-of-00131.safetensors.part000
COPY chunks/model-00112-of-00131.safetensors.part000 /model/chunks/model-00112-of-00131.safetensors.part000
COPY chunks/model-00113-of-00131.safetensors.part000 /model/chunks/model-00113-of-00131.safetensors.part000
COPY chunks/model-00114-of-00131.safetensors.part000 /model/chunks/model-00114-of-00131.safetensors.part000
COPY chunks/model-00115-of-00131.safetensors.part000 /model/chunks/model-00115-of-00131.safetensors.part000
COPY chunks/model-00116-of-00131.safetensors.part000 /model/chunks/model-00116-of-00131.safetensors.part000
COPY chunks/model-00117-of-00131.safetensors.part000 /model/chunks/model-00117-of-00131.safetensors.part000
COPY chunks/model-00118-of-00131.safetensors.part000 /model/chunks/model-00118-of-00131.safetensors.part000
COPY chunks/model-00119-of-00131.safetensors.part000 /model/chunks/model-00119-of-00131.safetensors.part000
COPY chunks/model-00120-of-00131.safetensors.part000 /model/chunks/model-00120-of-00131.safetensors.part000
COPY chunks/model-00121-of-00131.safetensors.part000 /model/chunks/model-00121-of-00131.safetensors.part000
COPY chunks/model-00122-of-00131.safetensors.part000 /model/chunks/model-00122-of-00131.safetensors.part000
COPY chunks/model-00123-of-00131.safetensors.part000 /model/chunks/model-00123-of-00131.safetensors.part000
COPY chunks/model-00124-of-00131.safetensors.part000 /model/chunks/model-00124-of-00131.safetensors.part000
COPY chunks/model-00125-of-00131.safetensors.part000 /model/chunks/model-00125-of-00131.safetensors.part000
COPY chunks/model-00126-of-00131.safetensors.part000 /model/chunks/model-00126-of-00131.safetensors.part000
COPY chunks/model-00127-of-00131.safetensors.part000 /model/chunks/model-00127-of-00131.safetensors.part000
COPY chunks/model-00128-of-00131.safetensors.part000 /model/chunks/model-00128-of-00131.safetensors.part000
COPY chunks/model-00129-of-00131.safetensors.part000 /model/chunks/model-00129-of-00131.safetensors.part000
COPY chunks/model-00130-of-00131.safetensors.part000 /model/chunks/model-00130-of-00131.safetensors.part000
COPY chunks/model-00131-of-00131.safetensors.part000 /model/chunks/model-00131-of-00131.safetensors.part000
COPY chunks/model.safetensors.index.json.part000 /model/chunks/model.safetensors.index.json.part000
COPY chunks/preprocessor_config.json.part000 /model/chunks/preprocessor_config.json.part000
COPY chunks/tokenizer.json.part000 /model/chunks/tokenizer.json.part000
COPY chunks/tokenizer_config.json.part000 /model/chunks/tokenizer_config.json.part000
COPY chunks/video_preprocessor_config.json.part000 /model/chunks/video_preprocessor_config.json.part000
COPY chunks/vocab.json.part000 /model/chunks/vocab.json.part000

# Entrypoint that reassembles model from chunks on first start
COPY entrypoint.sh /model/entrypoint.sh
RUN chmod +x /model/entrypoint.sh

# Where the final model file lands. Override with -v at runtime.
ENV MODEL_DIR=/model

ENTRYPOINT ["/model/entrypoint.sh"]
CMD ["bash"]
