# Auto-generated by gen_dockerfile.py
# Each COPY is a separate layer, all under 10 GB to satisfy GHCR.
# Repo: nvidia/Qwen3.8-Flash-Next-NVFP4
FROM ubuntu:22.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates bash coreutils && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /model
RUN mkdir -p /model/chunks

# Manifest first (small layer, helps debugging)
COPY manifest.json /model/manifest.json

# --- chunks (one COPY per chunk = one layer per chunk) ---
COPY chunks/.gitattributes.part000 /model/chunks/.gitattributes.part000
COPY chunks/README.md.part000 /model/chunks/README.md.part000
COPY chunks/chat_template.jinja.part000 /model/chunks/chat_template.jinja.part000
COPY chunks/config.json.part000 /model/chunks/config.json.part000
COPY chunks/generation_config.json.part000 /model/chunks/generation_config.json.part000
COPY chunks/hf_quant_config.json.part000 /model/chunks/hf_quant_config.json.part000
COPY chunks/merges.txt.part000 /model/chunks/merges.txt.part000
COPY chunks/model-00001-of-00010.safetensors.part000 /model/chunks/model-00001-of-00010.safetensors.part000
COPY chunks/model-00002-of-00010.safetensors.part000 /model/chunks/model-00002-of-00010.safetensors.part000
COPY chunks/model-00002-of-00010.safetensors.part001 /model/chunks/model-00002-of-00010.safetensors.part001
COPY chunks/model-00003-of-00010.safetensors.part000 /model/chunks/model-00003-of-00010.safetensors.part000
COPY chunks/model-00003-of-00010.safetensors.part001 /model/chunks/model-00003-of-00010.safetensors.part001
COPY chunks/model-00004-of-00010.safetensors.part000 /model/chunks/model-00004-of-00010.safetensors.part000
COPY chunks/model-00004-of-00010.safetensors.part001 /model/chunks/model-00004-of-00010.safetensors.part001
COPY chunks/model-00005-of-00010.safetensors.part000 /model/chunks/model-00005-of-00010.safetensors.part000
COPY chunks/model-00005-of-00010.safetensors.part001 /model/chunks/model-00005-of-00010.safetensors.part001
COPY chunks/model-00006-of-00010.safetensors.part000 /model/chunks/model-00006-of-00010.safetensors.part000
COPY chunks/model-00006-of-00010.safetensors.part001 /model/chunks/model-00006-of-00010.safetensors.part001
COPY chunks/model-00007-of-00010.safetensors.part000 /model/chunks/model-00007-of-00010.safetensors.part000
COPY chunks/model-00007-of-00010.safetensors.part001 /model/chunks/model-00007-of-00010.safetensors.part001
COPY chunks/model-00008-of-00010.safetensors.part000 /model/chunks/model-00008-of-00010.safetensors.part000
COPY chunks/model-00008-of-00010.safetensors.part001 /model/chunks/model-00008-of-00010.safetensors.part001
COPY chunks/model-00009-of-00010.safetensors.part000 /model/chunks/model-00009-of-00010.safetensors.part000
COPY chunks/model-00010-of-00010.safetensors.part000 /model/chunks/model-00010-of-00010.safetensors.part000
COPY chunks/model-fp8-mtp-ple.safetensors.part000 /model/chunks/model-fp8-mtp-ple.safetensors.part000
COPY chunks/model-fp8-mtp-ple.safetensors.part001 /model/chunks/model-fp8-mtp-ple.safetensors.part001
COPY chunks/model-fp8-mtp-ple.safetensors.part002 /model/chunks/model-fp8-mtp-ple.safetensors.part002
COPY chunks/model-fp8-mtp-ple.safetensors.part003 /model/chunks/model-fp8-mtp-ple.safetensors.part003
COPY chunks/model-fp8-mtp-ple.safetensors.part004 /model/chunks/model-fp8-mtp-ple.safetensors.part004
COPY chunks/model-fp8-mtp-ple.safetensors.part005 /model/chunks/model-fp8-mtp-ple.safetensors.part005
COPY chunks/model.safetensors.index.json.part000 /model/chunks/model.safetensors.index.json.part000
COPY chunks/preprocessor_config.json.part000 /model/chunks/preprocessor_config.json.part000
COPY chunks/processor_config.json.part000 /model/chunks/processor_config.json.part000
COPY chunks/tokenizer.json.part000 /model/chunks/tokenizer.json.part000
COPY chunks/tokenizer_config.json.part000 /model/chunks/tokenizer_config.json.part000
COPY chunks/video_preprocessor_config.json.part000 /model/chunks/video_preprocessor_config.json.part000
COPY chunks/vocab.json.part000 /model/chunks/vocab.json.part000

# Entrypoint that reassembles model from chunks on first start
COPY entrypoint.sh /model/entrypoint.sh
RUN chmod +x /model/entrypoint.sh

# Where the final model file lands. Override with -v at runtime.
ENV MODEL_DIR=/model

ENTRYPOINT ["/model/entrypoint.sh"]
CMD ["bash"]
