#!/usr/bin/env python3
"""
gen_dockerfile.py — Generate a Dockerfile + entrypoint.sh from manifest.json.

Strategy
--------
Each chunk is added to the image with its own COPY instruction. Docker turns
each COPY into a separate layer, so every layer is < 10 GB (matches the
GHCR per-layer limit).

The model is NOT reassembled at build time — reassembling at build time
would create one 50GB+ layer and blow the limit. Instead, the runtime
entrypoint concatenates the chunks into the final model file on first
container start, optionally into a mounted volume so the work happens once.

Layout inside the image:
  /model/manifest.json
  /model/chunks/<safe_name>.part000
  /model/chunks/<safe_name>.part001
  ...
  /model/entrypoint.sh   (reassembles + execs the real command)
"""
import os
import json
from pathlib import Path
from collections import defaultdict

MANIFEST  = Path(os.environ.get("MANIFEST", "./manifest.json"))
OUT_DIR   = Path(os.environ.get("OUT_DIR", "./chunks"))
DOCKERFILE = Path("Dockerfile")
ENTRYPOINT = Path("entrypoint.sh")


def main():
    manifest = json.loads(MANIFEST.read_text())
    chunks   = manifest["chunks"]
    repo_id  = manifest["repo_id"]

    # Group chunks per source file so the entrypoint knows which chunks
    # concatenate back into which original file.
    by_file = defaultdict(list)
    for c in chunks:
        by_file[c["source_file"]].append(c)
    # Make sure chunks within each file are ordered
    for f in by_file:
        by_file[f].sort(key=lambda c: c["chunk_index"])

    # ---------- Dockerfile ----------
    lines = [
        "# Auto-generated by gen_dockerfile.py",
        "# Each COPY is a separate layer, all under 10 GB to satisfy GHCR.",
        f"# Repo: {repo_id}",
        "FROM ubuntu:22.04",
        "",
        "RUN apt-get update && apt-get install -y --no-install-recommends \\",
        "    ca-certificates bash coreutils && \\",
        "    rm -rf /var/lib/apt/lists/*",
        "",
        "WORKDIR /model",
        "RUN mkdir -p /model/chunks",
        "",
        "# Manifest first (small layer, helps debugging)",
        "COPY manifest.json /model/manifest.json",
        "",
        "# --- chunks (one COPY per chunk = one layer per chunk) ---",
    ]

    # Sort chunks by name so the Dockerfile reads naturally
    for c in sorted(chunks, key=lambda c: c["chunk_name"]):
        lines.append(f"COPY chunks/{c['chunk_name']} /model/chunks/{c['chunk_name']}")

    lines.extend([
        "",
        "# Entrypoint that reassembles model from chunks on first start",
        "COPY entrypoint.sh /model/entrypoint.sh",
        "RUN chmod +x /model/entrypoint.sh",
        "",
        "# Where the final model file lands. Override with -v at runtime.",
        "ENV MODEL_DIR=/model",
        "",
        'ENTRYPOINT ["/model/entrypoint.sh"]',
        'CMD ["bash"]',
    ])
    DOCKERFILE.write_text("\n".join(lines) + "\n")

    # ---------- entrypoint.sh ----------
    ep = ["#!/usr/bin/env bash",
          "# Reassemble sharded model files from chunks on first start.",
          "# If MODEL_DIR is a mounted volume, the reassembly happens once",
          "# and persists across container restarts.",
          "set -euo pipefail",
          "",
          'cd /model',
          "",
          '# Helper: reassemble one file from its chunks',
          "assemble() {",
          '  local src="$1"   # e.g. "model-00001-of-00014.safetensors"',
          '  local dst="$2"   # e.g. "/vols/model/model-00001-of-00014.safetensors"',
          '  if [ -f "$dst" ]; then',
          '    echo "[entrypoint] $dst already exists, skipping"',
          '    return 0',
          '  fi',
          '  echo "[entrypoint] assembling $dst from chunks..."',
          '  local safe="${src//\\//_}"',
          '  local prefix="/model/chunks/${safe}.part"',
          '  # cat preserves byte order; parts are zero-padded',
          '  cat "${prefix}"* > "$dst.tmp"',
          '  mv "$dst.tmp" "$dst"',
          '  echo "[entrypoint] done: $dst"',
          "}",
          "",
          "main() {",
          '  mkdir -p "$MODEL_DIR"',
          '  # Read manifest and reassemble every source file',
          '  python3 - <<\'PY\'',
          "import json, os, subprocess, sys",
          "m = json.load(open('/model/manifest.json'))",
          "files = sorted({c['source_file'] for c in m['chunks']})",
          "for f in files:",
          "    dst = os.path.join(os.environ['MODEL_DIR'], f)",
          "    os.makedirs(os.path.dirname(dst) or '.', exist_ok=True)",
          "    if os.path.exists(dst):",
          "        print(f'skip {dst}', flush=True)",
          "        continue",
          "    safe = f.replace('/', '_')",
          "    parts = sorted(p for p in os.listdir('/model/chunks') if p.startswith(safe + '.part'))",
          "    cmd = ['cat'] + [f'/model/chunks/{p}' for p in parts]",
          "    print(f'assemble {dst} from {len(parts)} parts', flush=True)",
          "    with open(dst + '.tmp', 'wb') as out:",
          "        subprocess.run(cmd, stdout=out, check=True)",
          "    os.rename(dst + '.tmp', dst)",
          "PY",
          "}",
          "",
          "# Run reassembly, then hand off to the real command",
          "main",
          'exec "$@"',
          "",
    ]
    ENTRYPOINT.write_text("\n".join(ep))
    ENTRYPOINT.chmod(0o755)

    print(f"Wrote {DOCKERFILE} ({len(chunks)} chunk COPYs)")
    print(f"Wrote {ENTRYPOINT}")
    print()
    print("Next:")
    print("  cp Dockerfile entrypoint.sh manifest.json chunks/  <build-context>")
    print("  docker build -t ghcr.io/<user>/<model>:<tag> <build-context>")
    print("  docker push  ghcr.io/<user>/<model>:<tag>")


if __name__ == "__main__":
    main()