FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

RUN hf download \
    unsloth/Qwen3.8-Flash-Next \
    "model-00048-of-00131.safetensors" \
    "model-00049-of-00131.safetensors" \
    "model-00050-of-00131.safetensors" \
    "model-00051-of-00131.safetensors" \
    "model-00052-of-00131.safetensors" \
    "model-00053-of-00131.safetensors" \
    "model-00054-of-00131.safetensors" \
    "model-00055-of-00131.safetensors" \
    "model-00056-of-00131.safetensors" \
    "model-00057-of-00131.safetensors" \
    "model-00058-of-00131.safetensors" \
    "model-00059-of-00131.safetensors" \
    "model-00060-of-00131.safetensors"

