FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

RUN hf download \
    unsloth/Qwen3.8-Flash-Next \
    "model-00099-of-00131.safetensors" \
    "model-00100-of-00131.safetensors" \
    "model-00101-of-00131.safetensors" \
    "model-00102-of-00131.safetensors" \
    "model-00103-of-00131.safetensors" \
    "model-00104-of-00131.safetensors" \
    "model-00105-of-00131.safetensors" \
    "model-00106-of-00131.safetensors" \
    "model-00107-of-00131.safetensors" \
    "model-00108-of-00131.safetensors" \
    "model-00109-of-00131.safetensors" \
    "model-00110-of-00131.safetensors" \
    "model-00111-of-00131.safetensors"

