FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

RUN hf download \
    unsloth/Qwen3.8-Flash-Next \
    "model-00061-of-00131.safetensors" \
    "model-00062-of-00131.safetensors" \
    "model-00063-of-00131.safetensors" \
    "model-00064-of-00131.safetensors" \
    "model-00065-of-00131.safetensors" \
    "model-00066-of-00131.safetensors" \
    "model-00067-of-00131.safetensors" \
    "model-00068-of-00131.safetensors" \
    "model-00069-of-00131.safetensors" \
    "model-00070-of-00131.safetensors" \
    "model-00071-of-00131.safetensors" \
    "model-00072-of-00131.safetensors"

