# Part 7 of 7
# Shards: model-00125-of-00131.safetensors to model-00131-of-00131.safetensors
# Size: ~16.84 GB

FROM alpine:latest AS downloader
ARG HF_TOKEN
RUN apk add --no-cache git git-lfs ca-certificates
WORKDIR /downloads

RUN git lfs install && \
    git clone --depth 1 --filter=blob:none https://user:${HF_TOKEN}@huggingface.co/Qwen/Qwen3.8-Flash-Next repo && \
    cd repo && \
    git lfs pull \
        --include="model-00125-of-00131.safetensors" \
        --include="model-00126-of-00131.safetensors" \
        --include="model-00127-of-00131.safetensors" \
        --include="model-00128-of-00131.safetensors" \
        --include="model-00129-of-00131.safetensors" \
        --include="model-00130-of-00131.safetensors" \
        --include="model-00131-of-00131.safetensors" \
    && cd .. && \
    mkdir -p /model && \
    cd repo && \
    cp model-00125-of-00131.safetensors /model/ && \
    cp model-00126-of-00131.safetensors /model/ && \
    cp model-00127-of-00131.safetensors /model/ && \
    cp model-00128-of-00131.safetensors /model/ && \
    cp model-00129-of-00131.safetensors /model/ && \
    cp model-00130-of-00131.safetensors /model/ && \
    cp model-00131-of-00131.safetensors /model/ && \
    cd .. && rm -rf repo

FROM alpine:latest
WORKDIR /model

# Layer ~8.1 GB
COPY --from=downloader /model/model-00125-of-00131.safetensors /model/model-00125-of-00131.safetensors
COPY --from=downloader /model/model-00126-of-00131.safetensors /model/model-00126-of-00131.safetensors
COPY --from=downloader /model/model-00127-of-00131.safetensors /model/model-00127-of-00131.safetensors

# Layer ~8.8 GB
COPY --from=downloader /model/model-00128-of-00131.safetensors /model/model-00128-of-00131.safetensors
COPY --from=downloader /model/model-00129-of-00131.safetensors /model/model-00129-of-00131.safetensors
COPY --from=downloader /model/model-00130-of-00131.safetensors /model/model-00130-of-00131.safetensors
COPY --from=downloader /model/model-00131-of-00131.safetensors /model/model-00131-of-00131.safetensors

