FROM alpine:latest
RUN apk add --no-cache wget ca-certificates
WORKDIR /model

# ~5.4GB layer
RUN \
    wget -q "https://huggingface.co/nvidia/Qwen3.8-Flash-Next-NVFP4/resolve/main/model-00001-of-00010.safetensors" -O "/model/model-00001-of-00010.safetensors" && \
    wget -q "https://huggingface.co/nvidia/Qwen3.8-Flash-Next-NVFP4/resolve/main/model-00009-of-00010.safetensors" -O "/model/model-00009-of-00010.safetensors" && \
    wget -q "https://huggingface.co/nvidia/Qwen3.8-Flash-Next-NVFP4/resolve/main/model-00010-of-00010.safetensors" -O "/model/model-00010-of-00010.safetensors"
