FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

RUN hf download \
    nvidia/Qwen3.8-Flash-Next-NVFP4 \
    "model-00009-of-00010.safetensors" \
    "model-00010-of-00010.safetensors"

