# Part 6 of 7
# Shards: model-00103-of-00131.safetensors to model-00124-of-00131.safetensors
# Size: ~53.13 GB

FROM alpine:latest AS downloader
ARG HF_TOKEN
RUN apk add --no-cache git git-lfs ca-certificates
WORKDIR /downloads

RUN git lfs install && \
    git clone --depth 1 --filter=blob:none https://user:${HF_TOKEN}@huggingface.co/Qwen/Qwen3.8-Flash-Next repo && \
    cd repo && \
    git lfs pull \
        --include="model-00103-of-00131.safetensors" \
        --include="model-00104-of-00131.safetensors" \
        --include="model-00105-of-00131.safetensors" \
        --include="model-00106-of-00131.safetensors" \
        --include="model-00107-of-00131.safetensors" \
        --include="model-00108-of-00131.safetensors" \
        --include="model-00109-of-00131.safetensors" \
        --include="model-00110-of-00131.safetensors" \
        --include="model-00111-of-00131.safetensors" \
        --include="model-00112-of-00131.safetensors" \
        --include="model-00113-of-00131.safetensors" \
        --include="model-00114-of-00131.safetensors" \
        --include="model-00115-of-00131.safetensors" \
        --include="model-00116-of-00131.safetensors" \
        --include="model-00117-of-00131.safetensors" \
        --include="model-00118-of-00131.safetensors" \
        --include="model-00119-of-00131.safetensors" \
        --include="model-00120-of-00131.safetensors" \
        --include="model-00121-of-00131.safetensors" \
        --include="model-00122-of-00131.safetensors" \
        --include="model-00123-of-00131.safetensors" \
        --include="model-00124-of-00131.safetensors" \
    && cd .. && \
    mkdir -p /model && \
    cd repo && \
    cp model-00103-of-00131.safetensors /model/ && \
    cp model-00104-of-00131.safetensors /model/ && \
    cp model-00105-of-00131.safetensors /model/ && \
    cp model-00106-of-00131.safetensors /model/ && \
    cp model-00107-of-00131.safetensors /model/ && \
    cp model-00108-of-00131.safetensors /model/ && \
    cp model-00109-of-00131.safetensors /model/ && \
    cp model-00110-of-00131.safetensors /model/ && \
    cp model-00111-of-00131.safetensors /model/ && \
    cp model-00112-of-00131.safetensors /model/ && \
    cp model-00113-of-00131.safetensors /model/ && \
    cp model-00114-of-00131.safetensors /model/ && \
    cp model-00115-of-00131.safetensors /model/ && \
    cp model-00116-of-00131.safetensors /model/ && \
    cp model-00117-of-00131.safetensors /model/ && \
    cp model-00118-of-00131.safetensors /model/ && \
    cp model-00119-of-00131.safetensors /model/ && \
    cp model-00120-of-00131.safetensors /model/ && \
    cp model-00121-of-00131.safetensors /model/ && \
    cp model-00122-of-00131.safetensors /model/ && \
    cp model-00123-of-00131.safetensors /model/ && \
    cp model-00124-of-00131.safetensors /model/ && \
    cd .. && rm -rf repo

FROM alpine:latest
WORKDIR /model

# Layer ~9.7 GB
COPY --from=downloader /model/model-00103-of-00131.safetensors /model/model-00103-of-00131.safetensors
COPY --from=downloader /model/model-00104-of-00131.safetensors /model/model-00104-of-00131.safetensors
COPY --from=downloader /model/model-00105-of-00131.safetensors /model/model-00105-of-00131.safetensors
COPY --from=downloader /model/model-00106-of-00131.safetensors /model/model-00106-of-00131.safetensors

# Layer ~8.0 GB
COPY --from=downloader /model/model-00107-of-00131.safetensors /model/model-00107-of-00131.safetensors
COPY --from=downloader /model/model-00108-of-00131.safetensors /model/model-00108-of-00131.safetensors
COPY --from=downloader /model/model-00109-of-00131.safetensors /model/model-00109-of-00131.safetensors

# Layer ~9.7 GB
COPY --from=downloader /model/model-00110-of-00131.safetensors /model/model-00110-of-00131.safetensors
COPY --from=downloader /model/model-00111-of-00131.safetensors /model/model-00111-of-00131.safetensors
COPY --from=downloader /model/model-00112-of-00131.safetensors /model/model-00112-of-00131.safetensors
COPY --from=downloader /model/model-00113-of-00131.safetensors /model/model-00113-of-00131.safetensors

# Layer ~9.7 GB
COPY --from=downloader /model/model-00114-of-00131.safetensors /model/model-00114-of-00131.safetensors
COPY --from=downloader /model/model-00115-of-00131.safetensors /model/model-00115-of-00131.safetensors
COPY --from=downloader /model/model-00116-of-00131.safetensors /model/model-00116-of-00131.safetensors
COPY --from=downloader /model/model-00117-of-00131.safetensors /model/model-00117-of-00131.safetensors

# Layer ~9.7 GB
COPY --from=downloader /model/model-00118-of-00131.safetensors /model/model-00118-of-00131.safetensors
COPY --from=downloader /model/model-00119-of-00131.safetensors /model/model-00119-of-00131.safetensors
COPY --from=downloader /model/model-00120-of-00131.safetensors /model/model-00120-of-00131.safetensors
COPY --from=downloader /model/model-00121-of-00131.safetensors /model/model-00121-of-00131.safetensors

# Layer ~6.4 GB
COPY --from=downloader /model/model-00122-of-00131.safetensors /model/model-00122-of-00131.safetensors
COPY --from=downloader /model/model-00123-of-00131.safetensors /model/model-00123-of-00131.safetensors
COPY --from=downloader /model/model-00124-of-00131.safetensors /model/model-00124-of-00131.safetensors
