# Part 3 of 7
# Shards: model-00038-of-00131.safetensors to model-00059-of-00131.safetensors
# Size: ~53.03 GB

FROM alpine:latest AS downloader
ARG HF_TOKEN
RUN apk add --no-cache git git-lfs ca-certificates
WORKDIR /downloads

RUN GIT_LFS_SKIP_SMUDGE=1 git clone --depth 1 https://user:${HF_TOKEN}@huggingface.co/Qwen/Qwen3.8-Flash-Next repo && \
    cd repo && \
    git lfs pull \
        --include="model-00038-of-00131.safetensors" \
        --include="model-00039-of-00131.safetensors" \
        --include="model-00040-of-00131.safetensors" \
        --include="model-00041-of-00131.safetensors" \
        --include="model-00042-of-00131.safetensors" \
        --include="model-00043-of-00131.safetensors" \
        --include="model-00044-of-00131.safetensors" \
        --include="model-00045-of-00131.safetensors" \
        --include="model-00046-of-00131.safetensors" \
        --include="model-00047-of-00131.safetensors" \
        --include="model-00048-of-00131.safetensors" \
        --include="model-00049-of-00131.safetensors" \
        --include="model-00050-of-00131.safetensors" \
        --include="model-00051-of-00131.safetensors" \
        --include="model-00052-of-00131.safetensors" \
        --include="model-00053-of-00131.safetensors" \
        --include="model-00054-of-00131.safetensors" \
        --include="model-00055-of-00131.safetensors" \
        --include="model-00056-of-00131.safetensors" \
        --include="model-00057-of-00131.safetensors" \
        --include="model-00058-of-00131.safetensors" \
        --include="model-00059-of-00131.safetensors" \
    && cd .. && \
    mkdir -p /model && \
    cd repo && \
    cp model-00038-of-00131.safetensors /model/ && \
    cp model-00039-of-00131.safetensors /model/ && \
    cp model-00040-of-00131.safetensors /model/ && \
    cp model-00041-of-00131.safetensors /model/ && \
    cp model-00042-of-00131.safetensors /model/ && \
    cp model-00043-of-00131.safetensors /model/ && \
    cp model-00044-of-00131.safetensors /model/ && \
    cp model-00045-of-00131.safetensors /model/ && \
    cp model-00046-of-00131.safetensors /model/ && \
    cp model-00047-of-00131.safetensors /model/ && \
    cp model-00048-of-00131.safetensors /model/ && \
    cp model-00049-of-00131.safetensors /model/ && \
    cp model-00050-of-00131.safetensors /model/ && \
    cp model-00051-of-00131.safetensors /model/ && \
    cp model-00052-of-00131.safetensors /model/ && \
    cp model-00053-of-00131.safetensors /model/ && \
    cp model-00054-of-00131.safetensors /model/ && \
    cp model-00055-of-00131.safetensors /model/ && \
    cp model-00056-of-00131.safetensors /model/ && \
    cp model-00057-of-00131.safetensors /model/ && \
    cp model-00058-of-00131.safetensors /model/ && \
    cp model-00059-of-00131.safetensors /model/ && \
    cd .. && rm -rf repo

FROM alpine:latest
WORKDIR /model

# Layer ~9.7 GB
COPY --from=downloader /model/model-00038-of-00131.safetensors /model/model-00038-of-00131.safetensors
COPY --from=downloader /model/model-00039-of-00131.safetensors /model/model-00039-of-00131.safetensors
COPY --from=downloader /model/model-00040-of-00131.safetensors /model/model-00040-of-00131.safetensors
COPY --from=downloader /model/model-00041-of-00131.safetensors /model/model-00041-of-00131.safetensors

# Layer ~9.7 GB
COPY --from=downloader /model/model-00042-of-00131.safetensors /model/model-00042-of-00131.safetensors
COPY --from=downloader /model/model-00043-of-00131.safetensors /model/model-00043-of-00131.safetensors
COPY --from=downloader /model/model-00044-of-00131.safetensors /model/model-00044-of-00131.safetensors
COPY --from=downloader /model/model-00045-of-00131.safetensors /model/model-00045-of-00131.safetensors

# Layer ~9.7 GB
COPY --from=downloader /model/model-00046-of-00131.safetensors /model/model-00046-of-00131.safetensors
COPY --from=downloader /model/model-00047-of-00131.safetensors /model/model-00047-of-00131.safetensors
COPY --from=downloader /model/model-00048-of-00131.safetensors /model/model-00048-of-00131.safetensors
COPY --from=downloader /model/model-00049-of-00131.safetensors /model/model-00049-of-00131.safetensors

# Layer ~9.7 GB
COPY --from=downloader /model/model-00050-of-00131.safetensors /model/model-00050-of-00131.safetensors
COPY --from=downloader /model/model-00051-of-00131.safetensors /model/model-00051-of-00131.safetensors
COPY --from=downloader /model/model-00052-of-00131.safetensors /model/model-00052-of-00131.safetensors
COPY --from=downloader /model/model-00053-of-00131.safetensors /model/model-00053-of-00131.safetensors

# Layer ~9.7 GB
COPY --from=downloader /model/model-00054-of-00131.safetensors /model/model-00054-of-00131.safetensors
COPY --from=downloader /model/model-00055-of-00131.safetensors /model/model-00055-of-00131.safetensors
COPY --from=downloader /model/model-00056-of-00131.safetensors /model/model-00056-of-00131.safetensors
COPY --from=downloader /model/model-00057-of-00131.safetensors /model/model-00057-of-00131.safetensors

# Layer ~4.7 GB
COPY --from=downloader /model/model-00058-of-00131.safetensors /model/model-00058-of-00131.safetensors
COPY --from=downloader /model/model-00059-of-00131.safetensors /model/model-00059-of-00131.safetensors
