FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

RUN hf download \
    unsloth/Qwen3.8-Flash-Next \
    "model-00024-of-00131.safetensors" \
    "model-00025-of-00131.safetensors" \
    "model-00026-of-00131.safetensors" \
    "model-00027-of-00131.safetensors" \
    "model-00028-of-00131.safetensors" \
    "model-00029-of-00131.safetensors" \
    "model-00030-of-00131.safetensors" \
    "model-00031-of-00131.safetensors" \
    "model-00032-of-00131.safetensors" \
    "model-00033-of-00131.safetensors" \
    "model-00034-of-00131.safetensors"

