FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

RUN hf download \
    unsloth/Qwen3.8-Flash-Next \
    "model-00013-of-00131.safetensors" \
    "model-00014-of-00131.safetensors" \
    "model-00015-of-00131.safetensors" \
    "model-00016-of-00131.safetensors" \
    "model-00017-of-00131.safetensors" \
    "model-00018-of-00131.safetensors" \
    "model-00019-of-00131.safetensors" \
    "model-00020-of-00131.safetensors" \
    "model-00021-of-00131.safetensors" \
    "model-00022-of-00131.safetensors" \
    "model-00023-of-00131.safetensors"

