FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

RUN hf download \
    unsloth/Qwen3.8-Flash-Next \
    "model-00086-of-00131.safetensors" \
    "model-00087-of-00131.safetensors" \
    "model-00088-of-00131.safetensors" \
    "model-00089-of-00131.safetensors" \
    "model-00090-of-00131.safetensors" \
    "model-00091-of-00131.safetensors" \
    "model-00092-of-00131.safetensors" \
    "model-00093-of-00131.safetensors" \
    "model-00094-of-00131.safetensors" \
    "model-00095-of-00131.safetensors" \
    "model-00096-of-00131.safetensors" \
    "model-00097-of-00131.safetensors" \
    "model-00098-of-00131.safetensors"

