FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

RUN hf download \
    unsloth/Qwen3.8-Flash-Next \
    "model-00035-of-00131.safetensors" \
    "model-00036-of-00131.safetensors" \
    "model-00037-of-00131.safetensors" \
    "model-00038-of-00131.safetensors" \
    "model-00039-of-00131.safetensors" \
    "model-00040-of-00131.safetensors" \
    "model-00041-of-00131.safetensors" \
    "model-00042-of-00131.safetensors" \
    "model-00043-of-00131.safetensors" \
    "model-00044-of-00131.safetensors" \
    "model-00045-of-00131.safetensors" \
    "model-00046-of-00131.safetensors" \
    "model-00047-of-00131.safetensors"

