FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

RUN hf download \
    unsloth/Qwen3.8-Flash-Next \
    "model-00112-of-00131.safetensors" \
    "model-00113-of-00131.safetensors" \
    "model-00114-of-00131.safetensors" \
    "model-00115-of-00131.safetensors" \
    "model-00116-of-00131.safetensors" \
    "model-00117-of-00131.safetensors" \
    "model-00118-of-00131.safetensors" \
    "model-00119-of-00131.safetensors" \
    "model-00120-of-00131.safetensors" \
    "model-00121-of-00131.safetensors" \
    "model-00122-of-00131.safetensors" \
    "model-00123-of-00131.safetensors" \
    "model-00124-of-00131.safetensors" \
    "model-00125-of-00131.safetensors" \
    "model-00126-of-00131.safetensors" \
    "model-00127-of-00131.safetensors" \
    "model-00128-of-00131.safetensors" \
    "model-00129-of-00131.safetensors" \
    "model-00130-of-00131.safetensors" \
    "model-00131-of-00131.safetensors"

