FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

RUN hf download \
    unsloth/Qwen3.8-Flash-Next \
    "model-00073-of-00131.safetensors" \
    "model-00074-of-00131.safetensors" \
    "model-00075-of-00131.safetensors" \
    "model-00076-of-00131.safetensors" \
    "model-00077-of-00131.safetensors" \
    "model-00078-of-00131.safetensors" \
    "model-00079-of-00131.safetensors" \
    "model-00080-of-00131.safetensors" \
    "model-00081-of-00131.safetensors" \
    "model-00082-of-00131.safetensors" \
    "model-00083-of-00131.safetensors" \
    "model-00084-of-00131.safetensors" \
    "model-00085-of-00131.safetensors"

