FROM python:3.12-slim
ARG HF_TOKEN
ENV HF_TOKEN=$HF_TOKEN
RUN pip install --no-cache-dir huggingface_hub
RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*
WORKDIR /root/.cache/huggingface

# Config & tokenizer
RUN hf download \
    unsloth/Qwen3.8-Flash-Next \
    "LICENSE" \
    "README.md" \
    "chat_template.jinja" \
    "config.json" \
    "generation_config.json" \
    "merges.txt" \
    "model.safetensors.index.json" \
    "preprocessor_config.json" \
    "tokenizer.json" \
    "tokenizer_config.json" \
    "video_preprocessor_config.json" \
    "vocab.json" \
    "model-00001-of-00131.safetensors" \
    "model-00002-of-00131.safetensors" \
    "model-00003-of-00131.safetensors" \
    "model-00004-of-00131.safetensors" \
    "model-00005-of-00131.safetensors" \
    "model-00006-of-00131.safetensors" \
    "model-00007-of-00131.safetensors" \
    "model-00008-of-00131.safetensors" \
    "model-00009-of-00131.safetensors" \
    "model-00010-of-00131.safetensors" \
    "model-00011-of-00131.safetensors" \
    "model-00012-of-00131.safetensors"

